// SPDX-License-Identifier: Unicode-DFS-2016
// Effective region script overrides from Qt 5.15.7 locale availability.
// QLocale::matchingLocales -> QLocale(locale.name()).script(), retaining only
// rows different from QLocale(language).script(). Explicit script is handled
// before this lookup. Regenerate with the live oracle when changing CLDR data.
    {"az-IR", "Arab"},
    {"mn-CN", "Mong"},
    {"pa-PK", "Arab"},
    {"sd-IN", "Deva"},
    {"sr-ME", "Latn"},
    {"uz-AF", "Arab"},
    {"yue-CN", "Hans"},
    {"zh-HK", "Hant"},
    {"zh-MO", "Hant"},
    {"zh-TW", "Hant"},
