/*
 * SPDX-FileCopyrightText: 2026 S-09-b Task 1 palette handover fixture
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * Minimal KoConfig.h stub for the standalone palette byte-compat fixture.
 *
 * The real KoConfig.h is generated by CMake from KoConfig.h.cmake at the repo
 * root and carries platform/feature macros. This standalone fixture has no
 * configure step, so it vendors the same minimal set the kritapigment thin
 * shell uses (see .exec/shell/kritapigment/KoConfig.h): the macros the
 * libs/pigment headers actually consult. x86_64 is little-endian, so
 * WORDS_BIGENDIAN is intentionally left undefined.
 */
#ifdef __GNUC__
#  if defined(__x86_64__) || defined(__ppc64__) || defined(__aarch64__)
#    define ENV64BIT
#  else
#    define ENV32BIT
#  endif
#endif

#define HAVE_OPENEXR 1
#define HAVE_LCMS2 1
