#!/usr/bin/env bash
# R-52 blur 内核对拍：Qt 侧链真 Qt5Gui，Pk 侧链 libpkrender.a（走 CMake target
# blur_kernel_oracle_pk，Qt-free）。两侧输出逐行 diff，再把 Qt 侧输出落成金标。
#
# 形态与同目录的 run_shape_primitive.sh 逐段一致（R-51 交付，本机 macOS arm64 实测
# 可跑）。与那两个跑不了的旧脚本（run_brush_gradient.sh / run_brush_transform.sh）
# 的两处差别同样照抄：
#   1. 环境脚本位置从约定位置探测，不写死 /mnt/ssd-disk/... 的 Linux 路径；
#   2. 不使用 GNU ld 专有的 --start-group/--end-group（ld64 不认），
#      Pk 侧链接整个交给 CMake。
set -eo pipefail

render_root=$(cd "$(dirname "$0")/.." && pwd)

# 依赖前缀所在目录（krita-ci-env）是**工作空间根的同级**。本脚本既可能从主
# checkout 跑，也可能从 <工作空间>/krita-worktrees/<ID>/ 的 worktree 跑——两者
# 离工作空间根的层数不同，所以不数层数，直接向上找 `krita-ci-env/env`。
# 约定默认：<工作空间>/../krita-ci-env/env（见 .exec/shell/README.md）。
find_env_script()
{
    local dir="$render_root"
    while [[ "$dir" != "/" ]]; do
        if [[ -f "$dir/krita-ci-env/env" ]]; then printf '%s\n' "$dir/krita-ci-env/env"; return 0; fi
        dir=$(dirname "$dir")
    done
    return 1
}
env_script="${KRITA_CI_ENV:-}"
if [[ -z "$env_script" ]]; then
    env_script=$(find_env_script) || {
        printf 'cannot locate krita-ci-env/env above %s\n' "$render_root" >&2
        printf 'set KRITA_CI_ENV=<path to krita-ci-env/env> and retry\n' >&2
        exit 2
    }
fi
if [[ ! -f "$env_script" ]]; then
    printf 'dependency env script not found: %s\n' "$env_script" >&2
    exit 2
fi
# shellcheck disable=SC1090
source "$env_script"
set -u
if [[ -n "${KDECI_CC_CACHE:-}" ]]; then export CCACHE_DIR="$KDECI_CC_CACHE"; fi

build_dir="${PK_RENDER_BUILD_DIR:-$render_root/build}"
oracle_build="$build_dir/oracle-blur-kernel"
mkdir -p "$oracle_build"

# macOS 上薄壳必须显式给部署目标：pk/ 层用到 std::to_chars 的浮点重载
# （macOS >= 13.3），而本机 env 把 MACOSX_DEPLOYMENT_TARGET 设成 10.15。
# 见 <工作空间>/../krita-ci-env/MACOS-SHELL-NOTES.md §2。
extra_cmake_args=()
if [[ "$(uname -s)" == "Darwin" ]]; then
    extra_cmake_args+=(-DCMAKE_OSX_DEPLOYMENT_TARGET=13.3)
fi

cmake -S "$render_root" -B "$build_dir" -G Ninja \
    "${extra_cmake_args[@]}" \
    -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
# test_blur_kernel 也在这里建出来：本脚本产出金标，测试是金标的消费者，
# 两条命令连跑（脚本 → ctest）时 ctest 找不到二进制就没有意义。
ninja -C "$build_dir" blur_kernel_oracle_pk test_blur_kernel

# ── Qt 侧（唯一链真 Qt 的一步；不进任何产物）────────────────────────────────
qt_flags=$(pkg-config --cflags --libs Qt5Gui)
qt_rpath=()
if [[ "$(uname -s)" == "Darwin" ]]; then
    # macOS 上 Qt 以 framework 形式安装，二进制需要显式 rpath 才起得来
    # （否则 dyld: Library not loaded: @rpath/QtGui.framework/...）。
    qt_libdir=$(pkg-config --variable=libdir Qt5Gui)
    qt_rpath+=(-Wl,-rpath,"$qt_libdir")
fi

ccache c++ -std=c++17 -fPIC -DPK_BLUR_QT_ORACLE \
    "$render_root/oracle/blur_kernel_oracle.cpp" \
    $qt_flags "${qt_rpath[@]}" -o "$oracle_build/qt"

"$oracle_build/qt" > "$oracle_build/qt.raw.txt"
"$build_dir/blur_kernel_oracle_pk" > "$oracle_build/pk.raw.txt"

# 两侧各自的第一行是自报家门的 provenance（backend Qt5Gui / PkImageRasterBackend），
# 按定义不同，不参与对拍——比的是它后面那 N 行逐用例摘要。
grep -v '^backend ' "$oracle_build/qt.raw.txt" > "$oracle_build/qt.txt"
grep -v '^backend ' "$oracle_build/pk.raw.txt" > "$oracle_build/pk.txt"

if ! diff -u "$oracle_build/qt.txt" "$oracle_build/pk.txt"; then
    printf 'blur kernel oracle DIVERGED\n' >&2
    exit 1
fi

# 金标只由 Qt 侧产出，且带出生证明（哪个 Qt 版本、什么时候、谁生成的）。
{
    printf '# generated by pk/render/oracle/run_blur_kernel.sh\n'
    printf '# qt=%s\n' "$(pkg-config --modversion Qt5Gui)"
    printf '# backend=%s\n' "$(head -1 "$oracle_build/qt.raw.txt" | cut -d' ' -f2)"
    cat "$oracle_build/qt.txt"
} > "$render_root/oracle/blur_kernel_golden.txt"

printf 'blur kernel Qt oracle: identical (%s cases)\n' \
    "$(wc -l < "$oracle_build/qt.txt" | tr -d ' ')"
