#!/usr/bin/env bash
# R-54 批 2：PkSvgPainterBackend 的椭圆/多边形/弧对拍。
#
# 与 run_shape_primitive.sh 的唯一形态差别（R-54 §1.3 实测逼出来的）：批 2 两侧的产物是
# **SVG 文档**，而两份文档的**文本按定义不同**（Qt 对 drawEllipse 产出 `<ellipse>`、数字格式/
# 属性集合/顺序全不同）→ 判据④不能做文本 diff。比较面改成：**同一个渲染器**
# （真 Qt QSvgRenderer）把两侧各自的文档渲染成同尺寸 32×32 ARGB32 图后逐像素比。
#   1. Pk 侧（Qt-free，CMake target svg_primitive_oracle_pk）逐用例产出 `<名字>\t<文档正文>`；
#   2. Qt 侧（本脚本手工编，链 Qt5Svg）读那份输出当比较器，逐例渲染两份文档、报 mismatch。
#
# 本机 macOS arm64：与 run_shape_primitive.sh 同样的两处适配（不写死 Linux 环境路径、
# Pk 侧链接整个交给 CMake），Qt 侧多了 Qt5Svg。
set -eo pipefail

render_root=$(cd "$(dirname "$0")/.." && pwd)

# 依赖前缀 krita-ci-env 是**工作空间根的同级**，而脚本既可能从主 checkout 跑、也可能从
# <工作空间>/krita-worktrees/<ID>/ 的 worktree 跑——不数层数，直接向上找 krita-ci-env/env。
find_env_script()
{
    local dir="$render_root"
    while [[ "$dir" != "/" ]]; do
        if [[ -f "$dir/krita-ci-env/env" ]]; then printf '%s\n' "$dir/krita-ci-env/env"; return 0; fi
        dir=$(dirname "$dir")
    done
    return 1
}
env_script="${KRITA_CI_ENV:-}"
if [[ -z "$env_script" ]]; then
    env_script=$(find_env_script) || {
        printf 'cannot locate krita-ci-env/env above %s\n' "$render_root" >&2
        printf 'set KRITA_CI_ENV=<path to krita-ci-env/env> and retry\n' >&2
        exit 2
    }
fi
if [[ ! -f "$env_script" ]]; then
    printf 'dependency env script not found: %s\n' "$env_script" >&2
    exit 2
fi
# shellcheck disable=SC1090
source "$env_script"
set -u
if [[ -n "${KDECI_CC_CACHE:-}" ]]; then export CCACHE_DIR="$KDECI_CC_CACHE"; fi

build_dir="${PK_RENDER_BUILD_DIR:-$render_root/build}"
oracle_build="$build_dir/oracle-svg-primitive"
mkdir -p "$oracle_build"

# macOS 上薄壳必须显式给部署目标：pk/ 层用到 std::to_chars 的浮点重载（macOS >= 13.3），
# 而本机 env 把 MACOSX_DEPLOYMENT_TARGET 设成 10.15。形态与 run_shape_primitive.sh 同。
extra_cmake_args=()
if [[ "$(uname -s)" == "Darwin" ]]; then
    extra_cmake_args+=(-DCMAKE_OSX_DEPLOYMENT_TARGET=13.3)
fi

cmake -S "$render_root" -B "$build_dir" -G Ninja \
    "${extra_cmake_args[@]}" \
    -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
ninja -C "$build_dir" svg_primitive_oracle_pk

# ── Qt 侧（唯一链真 Qt 的一步；不进任何产物）────────────────────────────────
qt_flags=$(pkg-config --cflags --libs Qt5Gui Qt5Svg)
qt_rpath=()
if [[ "$(uname -s)" == "Darwin" ]]; then
    qt_libdir=$(pkg-config --variable=libdir Qt5Svg)
    qt_rpath+=(-Wl,-rpath,"$qt_libdir")
fi

ccache c++ -std=c++17 -fPIC -DPK_SVG_QT_ORACLE \
    -I"$render_root/oracle" \
    "$render_root/oracle/svg_primitive_qt.cpp" \
    $qt_flags "${qt_rpath[@]}" -o "$oracle_build/qt"

# 形态契约要求「必须能 ldd 看到真的链上了 Qt」——本机 macOS 用 otool -L。
if [[ "$(uname -s)" == "Darwin" ]]; then
    otool -L "$oracle_build/qt" | grep -qi 'Qt' || {
        printf 'Qt-side comparator does not link Qt\n' >&2; exit 2; }
else
    ldd "$oracle_build/qt" | grep -qi 'qt' || {
        printf 'Qt-side comparator does not link Qt\n' >&2; exit 2; }
fi

"$build_dir/svg_primitive_oracle_pk" > "$oracle_build/pk.raw.txt"
"$oracle_build/qt" "$oracle_build/pk.raw.txt" "$oracle_build/golden.body.txt" \
    > "$oracle_build/qt.stdout.txt"
diff_line=$(grep -E '^DIFF total=' "$oracle_build/qt.stdout.txt" | tail -1)
if [[ -z "$diff_line" ]]; then
    printf 'comparator printed no DIFF summary line\n' >&2
    cat "$oracle_build/qt.stdout.txt" >&2
    exit 2
fi
mismatch=$(sed -E 's/.*mismatch=([0-9]+).*/\1/' <<<"$diff_line")
total=$(sed -E 's/.*total=([0-9]+).*/\1/' <<<"$diff_line")

if [[ "$mismatch" != "0" ]]; then
    printf 'svg primitive oracle DIVERGED: %s\n' "$diff_line" >&2
    cat "$oracle_build/qt.stdout.txt" >&2
    exit 1
fi

# 金标只由 Qt 侧比较器产出，且带出生证明（哪个 Qt 版本、谁生成的）。`# blank=` 那行随
# golden.body.txt 一并落盘——它是 Qt 侧测出的空画布摘要，供 Qt-free 的 ctest 数退化用例。
{
    printf '# generated by pk/render/oracle/run_svg_primitive.sh\n'
    printf '# qt=%s\n' "$(pkg-config --modversion Qt5Svg)"
    printf '# comparator=QSvgRenderer (Qt5Svg %s) + QSvgGenerator\n' "$(pkg-config --modversion Qt5Svg)"
    cat "$oracle_build/golden.body.txt"
} > "$render_root/oracle/svg_primitive_golden.txt"

printf 'svg primitive Qt oracle: identical (%s cases)\n' "$total"
