#!/usr/bin/env bash
# R-55 文字对拍：Qt 侧链真 Qt5Gui，Pk 侧链 libpkrender.a（走 CMake target
# text_oracle_pk，Qt-free）。两侧输出逐行 diff。
#
# **引擎条件化**（形态照 pk/font/oracle/compare.cmake，人 2026-09-12 裁决）：
#   文字类对拍的参照系本身依赖平台——Qt 在 Linux 走 FreeType、macOS 走 CoreText。
#   跑比较之前先做一次**实测的能力探测**：数 Qt 真正那份 QtGui 里的 QFontEngineFT
#   符号条数。
#     >0           → Qt 走 FreeType，参照系成立：照旧真跑两侧比较，金标由 Qt 侧产出。
#     ==0 且分母 >0 → 正面证据说明 Qt 无 FreeType 引擎：打印 SKIP、**不跑 Qt 侧**、
#                     把 Pk 侧输出落成金标（出生证明栏如实写 Pk），退出 0。
#     探测不到     → QtGui 找不到或 nm 没读到东西：探测无效，**不跳过**，照旧真跑。
#   打印的全是实测数字（QtGui 路径、nm 行数、符号计数），没有一处硬编码
#   「这是 macOS 所以跳过」。
#
# 与 run_shape_primitive.sh 的三处差别：
#   1. 上面那条引擎条件化；
#   2. 显式 export FONTCONFIG_PATH（plan §6 第 5 条）——不设它 fontconfig 会打印
#      `Cannot load default config file` 且 CJK 回退会变，Pk 侧结果随环境漂；
#   3. SKIP 分支的 DIFF 行写 `mismatch=NA` 而不是 `0`——Qt 侧根本没跑，
#      「0」会被读成「比过了、没差」，那是假的。
set -eo pipefail

render_root=$(cd "$(dirname "$0")/.." && pwd)

# 依赖前缀所在目录（krita-ci-env）是**工作空间根的同级**。本脚本既可能从主
# checkout 跑，也可能从 <工作空间>/krita-worktrees/<ID>/ 的 worktree 跑——两者
# 离工作空间根的层数不同，所以不数层数，直接向上找 `krita-ci-env/env`。
find_env_script()
{
    local dir="$render_root"
    while [[ "$dir" != "/" ]]; do
        if [[ -f "$dir/krita-ci-env/env" ]]; then printf '%s\n' "$dir/krita-ci-env/env"; return 0; fi
        dir=$(dirname "$dir")
    done
    return 1
}
env_script="${KRITA_CI_ENV:-}"
if [[ -z "$env_script" ]]; then
    env_script=$(find_env_script) || {
        printf 'cannot locate krita-ci-env/env above %s\n' "$render_root" >&2
        printf 'set KRITA_CI_ENV=<path to krita-ci-env/env> and retry\n' >&2
        exit 2
    }
fi
if [[ ! -f "$env_script" ]]; then
    printf 'dependency env script not found: %s\n' "$env_script" >&2
    exit 2
fi
# shellcheck disable=SC1090
source "$env_script"
set -u
if [[ -n "${KDECI_CC_CACHE:-}" ]]; then export CCACHE_DIR="$KDECI_CC_CACHE"; fi

# plan §6 第 5 条：fontconfig 配置显式指向 CI 前缀，否则 Pk 侧结果随环境漂。
ci_prefix=$(cd "$(dirname "$env_script")" && pwd)
if [[ -d "$ci_prefix/_install/etc/fonts" ]]; then
    export FONTCONFIG_PATH="$ci_prefix/_install/etc/fonts"
fi
if [[ -z "${FONTCONFIG_PATH:-}" ]]; then
    printf 'WARNING: FONTCONFIG_PATH unset (no %s/_install/etc/fonts); Pk-side results may drift\n' \
        "$ci_prefix" >&2
fi

build_dir="${PK_RENDER_BUILD_DIR:-$render_root/build}"
oracle_build="$build_dir/oracle-text"
mkdir -p "$oracle_build"

# macOS 上薄壳必须显式给部署目标：pk/ 层用到 std::to_chars 的浮点重载
# （macOS >= 13.3），而本机 env 把 MACOSX_DEPLOYMENT_TARGET 设成 10.15。
extra_cmake_args=()
if [[ "$(uname -s)" == "Darwin" ]]; then
    extra_cmake_args+=(-DCMAKE_OSX_DEPLOYMENT_TARGET=13.3)
fi

cmake -S "$render_root" -B "$build_dir" -G Ninja \
    "${extra_cmake_args[@]}" \
    -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
ninja -C "$build_dir" text_oracle_pk

"$build_dir/text_oracle_pk" > "$oracle_build/pk.raw.txt"
# provenance 行按定义两侧不同，剥掉再比（R-51 踩过这一行）。
grep -v '^backend ' "$oracle_build/pk.raw.txt" > "$oracle_build/pk.txt"
pk_total=$(grep -c '^DIFFTAG ' "$oracle_build/pk.txt" | tr -d ' ')

write_pk_born_golden()
{
    # 出生证明栏**如实**写 Pk——不许伪造成 Qt 金标（plan §3.4 / §6 第 6 条）。
    {
        printf '# generated by pk/render/oracle/run_text.sh\n'
        printf '# born=Pk\n'
        printf '# backend=%s\n' "$(head -1 "$oracle_build/pk.raw.txt" | cut -d' ' -f2)"
        printf '# qt=%s\n' "$(pkg-config --modversion Qt5Gui)"
        printf '# reason=Qt on this host has no FreeType text engine (QFontEngineFT=%s of nm_lines=%s); a Qt-born golden is owed, see plan §6 item 6\n' \
            "$ft_count" "$nm_lines"
        cat "$oracle_build/pk.txt"
    } > "$render_root/oracle/text_golden.txt"
}

# ── 能力探测：Qt 有没有 FreeType 文字引擎（实测，不硬编码平台）───────────────
qt_libdir=$(pkg-config --variable=libdir Qt5Gui)
qtgui=""
for cand in \
    "$qt_libdir/QtGui.framework/Versions/5/QtGui" \
    "$qt_libdir/libQt5Gui.dylib" \
    "$qt_libdir/libQt5Gui.so" \
    "$qt_libdir/libQt5Gui.so.5"; do
    if [[ -f "$cand" ]]; then qtgui="$cand"; break; fi
done

if [[ -z "$qtgui" ]]; then
    printf 'text oracle probe: QtGui=NOT FOUND under %s — probe invalid, not skipping\n' \
        "$qt_libdir" >&2
    nm_lines=0
    ft_count=0
else
    nm_lines=$(nm -a "$qtgui" 2>/dev/null | wc -l | tr -d ' ')
    ft_count=$(nm -a "$qtgui" 2>/dev/null | grep -c 'QFontEngineFT' || true)
    printf 'text oracle probe: QtGui=%s nm_lines=%s QFontEngineFT=%s\n' \
        "$qtgui" "$nm_lines" "$ft_count"
fi

# 判据：**分母 > 0 且分子 == 0** 才算「正面证据说明没有引擎」。
# 探测不到（nm 读空 / QtGui 找不到 / Qt 整个没有）一律**不跳过**——宁可在本机红着，
# 也不把「探测失败」当成「无引擎」，那会让带 FreeType 的宿主假装通过。
if [[ "$nm_lines" != "0" && "$ft_count" == "0" ]]; then
    printf 'SKIP: Qt has no FreeType text engine (%s)\n' "$ft_count"
    write_pk_born_golden
    printf 'text golden: Pk-side produced; Qt birth certificate owed (see plan §6 item 6)\n'
    printf 'DIFF total=%s mismatch=NA (Qt side not run: reference not available on this host)\n' \
        "$pk_total"
    exit 0
fi

# ── Qt 侧（唯一链真 Qt 的一步；不进任何产物）────────────────────────────────
qt_flags=$(pkg-config --cflags --libs Qt5Gui)
qt_rpath=()
if [[ "$(uname -s)" == "Darwin" ]]; then
    # macOS 上 Qt 以 framework 形式安装，二进制需要显式 rpath 才起得来
    # （否则 dyld: Library not loaded: @rpath/QtGui.framework/...）。
    qt_rpath+=(-Wl,-rpath,"$qt_libdir")
fi

ccache c++ -std=c++17 -fPIC -DPK_TEXT_QT_ORACLE \
    "$render_root/oracle/text_oracle.cpp" \
    $qt_flags "${qt_rpath[@]}" -o "$oracle_build/qt"

# Qt 侧建 QGuiApplication + 默认字体库 ⇒ 无头环境下必须显式 offscreen
# （同 pk/font/oracle/CMakeLists.txt 给 font_pixels_qt_comparison 设的那条）。
QT_QPA_PLATFORM=offscreen "$oracle_build/qt" > "$oracle_build/qt.raw.txt"
grep -v '^backend ' "$oracle_build/qt.raw.txt" > "$oracle_build/qt.txt"

# mismatch = Qt 侧有、Pk 侧没有的行数（默认 diff 的 `< ` 前缀）。
mismatch=0
if ! diff "$oracle_build/qt.txt" "$oracle_build/pk.txt" > "$oracle_build/diff.txt"; then
    mismatch=$(grep -c '^< ' "$oracle_build/diff.txt" || true)
fi
printf 'DIFF total=%s mismatch=%s\n' "$pk_total" "$mismatch"

if [[ "$mismatch" != "0" ]]; then
    cat "$oracle_build/diff.txt" >&2
    printf 'text oracle DIVERGED\n' >&2
    exit 1
fi

# 金标只由 Qt 侧产出，且带出生证明（哪个 Qt 版本、谁生成的）。
{
    printf '# generated by pk/render/oracle/run_text.sh\n'
    printf '# born=Qt\n'
    printf '# qt=%s\n' "$(pkg-config --modversion Qt5Gui)"
    printf '# backend=%s\n' "$(head -1 "$oracle_build/qt.raw.txt" | cut -d' ' -f2)"
    cat "$oracle_build/qt.txt"
} > "$render_root/oracle/text_golden.txt"

printf 'text Qt oracle: identical (%s cases)\n' "$pk_total"
