#!/usr/bin/env python3
"""Generate the constexpr UTF-16 mapping tables consumed by PkString."""

from __future__ import annotations

import pathlib
import sys


def utf16_units(codepoints: tuple[int, ...]) -> tuple[int, ...]:
    units: list[int] = []
    for cp in codepoints:
        if cp <= 0xFFFF:
            units.append(cp)
        else:
            value = cp - 0x10000
            units.extend((0xD800 + (value >> 10), 0xDC00 + (value & 0x3FF)))
    return tuple(units)


def emit_table(name: str, mapping: dict[int, tuple[int, ...]]) -> list[str]:
    values: list[int] = []
    entries: list[tuple[int, int, int]] = []
    for cp, result in sorted(mapping.items()):
        encoded = utf16_units(result)
        entries.append((cp, len(values), len(encoded)))
        values.extend(encoded)

    lines = [f"inline constexpr char16_t k{name}Values[] = {{"]
    for start in range(0, len(values), 12):
        chunk = ", ".join(f"0x{value:04X}" for value in values[start:start + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append(f"inline constexpr Mapping k{name}Mappings[] = {{")
    for cp, offset, length in entries:
        lines.append(f"    {{0x{cp:06X}, {offset}, {length}}},")
    lines.append("};")
    return lines


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: generate_case_data.py CaseMapping-13.0.0.txt PkUnicodeCaseData.h", file=sys.stderr)
        return 2
    source = pathlib.Path(sys.argv[1])
    output = pathlib.Path(sys.argv[2])
    mappings: dict[str, dict[int, tuple[int, ...]]] = {"L": {}, "U": {}}
    for raw_line in source.read_text(encoding="ascii").splitlines():
        if not raw_line or raw_line.startswith("#"):
            continue
        direction, cp_text, result_text = raw_line.split(";")
        cp = int(cp_text, 16)
        result = tuple(int(token, 16) for token in result_text.split())
        if direction not in mappings or not result:
            raise SystemExit(f"invalid mapping line: {raw_line}")
        mappings[direction][cp] = result

    lines = [
        "#pragma once",
        "",
        "// Generated by generate_case_data.py from Unicode CaseMapping-13.0.0.txt.",
        "// Do not edit by hand. See README.md and LICENSE.UNICODE.",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace PkUnicodeCaseData {",
        "struct Mapping {",
        "    std::uint32_t source;",
        "    std::uint16_t offset;",
        "    std::uint8_t length;",
        "};",
        "",
    ]
    lines.extend(emit_table("Lower", mappings["L"]))
    lines.append("")
    lines.extend(emit_table("Upper", mappings["U"]))
    lines.extend(["", "} // namespace PkUnicodeCaseData", ""])
    output.write_text("\n".join(lines), encoding="ascii")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
